postgres:
    image: postgres:9.5
    environment:
        POSTGRES_PASSWORD: z0B5UzJpNfXq-zbR
    volumes:
        - ./postgres/data:/var/lib/postgresql/data
    restart: always

redmine:
    image: redmine:3.3
    volumes:
        - ./redmine/files:/usr/src/redmine/files
        - ./redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
        - ./redmine/config/database.yml:/usr/src/redmine/config/database.yml
        - ./redmine/plugins:/usr/src/redmine/plugins
        - ./redmine/themes:/usr/src/redmine/public/themes
        - ./redmine/repos:/repos
    links:
        - postgres
    restart: always

nginx:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./nginx/ssl:/etc/nginx/ssl
    links:
        - redmine
    restart: always
